import PyPDF2
n=int(input("Enter a page number from 1st pdf to merge:"))
pw=PyPDF2.PdfWriter()
pf=open('1.pdf','rb')
pr=PyPDF2.PdfReader(pf)
pw.add_page(pr.pages[n-1])
n=int(input("Enter a page number from 2nd pdf to merge:"))
pf=open('2.pdf','rb')
pr=PyPDF2.PdfReader(pf)
pw.add_page(pr.pages[n-1])
n=int(input("Enter a page number from 3rd pdf to merge:"))
pf=open('3.pdf','rb')
pr=PyPDF2.PdfReader(pf)
pw.add_page(pr.pages[n-1])
output=open('output.pdf',"wb")
pw.write(output)
output.close()
pf.close()
pw.close()
print('New pdf created succcessfully')
